In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(3,)

In [6]:
arr.dtype

dtype('int64')

In [7]:
arr.size

3

In [8]:
arr.ndim

1

In [9]:
###2d

In [16]:
arr1 = np.array([[1,2,3],[1,2,3]])

In [18]:
arr1


array([[1, 2, 3],
       [1, 2, 3]])

In [20]:
arr2 = np.array([[[1,2,3],[1,2,3]]])

In [21]:
arr2

array([[[1, 2, 3],
        [1, 2, 3]]])

In [22]:
arr2.ndim

3

In [26]:
arr4 = np.array([[[   [1,2,3],[1,2,3]    ]]])
arr4

array([[[[1, 2, 3],
         [1, 2, 3]]]])

In [27]:
arr4.ndim

4

In [28]:
a = np.random.randint(1,2)

In [30]:
a

0

In [41]:
a = np.random.rand(3,2,3)
a

array([[[0.57428324, 0.00311499, 0.16313883],
        [0.74007735, 0.17159551, 0.76030702]],

       [[0.48592894, 0.76702866, 0.34826474],
        [0.55411784, 0.47993307, 0.50684013]],

       [[0.63808863, 0.98503548, 0.79057515],
        [0.51264678, 0.7096532 , 0.74916261]]])

In [45]:
zero = np.zeros((3,2,3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
full = np.full((3,2,3),8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [51]:
a.sort()

In [52]:
a

array([[[0.00311499, 0.16313883, 0.57428324],
        [0.17159551, 0.74007735, 0.76030702]],

       [[0.34826474, 0.48592894, 0.76702866],
        [0.47993307, 0.50684013, 0.55411784]],

       [[0.63808863, 0.79057515, 0.98503548],
        [0.51264678, 0.7096532 , 0.74916261]]])

In [61]:
a10 = np.array([[[1, 20, 8],
        [58, 28, 38]],

       [[68, 778, 833],
        [788, 458, 812]],

       [[18, 28, 78],
        [28, 348, 8123]]])

In [62]:
a10

array([[[   1,   20,    8],
        [  58,   28,   38]],

       [[  68,  778,  833],
        [ 788,  458,  812]],

       [[  18,   28,   78],
        [  28,  348, 8123]]])

In [63]:
a10.sort()

In [64]:
a10

array([[[   1,    8,   20],
        [  28,   38,   58]],

       [[  68,  778,  833],
        [ 458,  788,  812]],

       [[  18,   28,   78],
        [  28,  348, 8123]]])

In [65]:
a11 = np.array([[[122, 210, 18],
        [528, 228, 3228]],

       [[683, 7378, 8333],
        [788, 458, 812]],

       [[128, 248, 738],
        [238, 3438, 81223]]])

In [66]:
np.add(a10,a11)

array([[[  123,   218,    38],
        [  556,   266,  3286]],

       [[  751,  8156,  9166],
        [ 1246,  1246,  1624]],

       [[  146,   276,   816],
        [  266,  3786, 89346]]])

In [68]:
np.subtract(a10,a11)

array([[[  -121,   -202,      2],
        [  -500,   -190,  -3170]],

       [[  -615,  -6600,  -7500],
        [  -330,    330,      0]],

       [[  -110,   -220,   -660],
        [  -210,  -3090, -73100]]])

In [69]:
np.multiply(a10,a11)

array([[[      122,      1680,       360],
        [    14784,      8664,    187224]],

       [[    46444,   5740084,   6941389],
        [   360904,    360904,    659344]],

       [[     2304,      6944,     57564],
        [     6664,   1196424, 659774429]]])

In [70]:
np.divide(a10,a11)

array([[[0.00819672, 0.03809524, 1.11111111],
        [0.0530303 , 0.16666667, 0.01796778]],

       [[0.09956076, 0.10544863, 0.099964  ],
        [0.58121827, 1.72052402, 1.        ]],

       [[0.140625  , 0.11290323, 0.10569106],
        [0.11764706, 0.10122164, 0.10000862]]])

In [71]:
np.power(4,2)

np.int64(16)

In [76]:
b = np.zeros((3,2,3))

In [77]:
b

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [82]:
c= np.ones((3,2,3))

In [83]:
d= np.append(b,c,axis=1)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [92]:
d= np.append(b,c,axis=1)

In [95]:
newArray = np.insert(b,2,c,axis=0)

In [96]:
newArray

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [101]:
np.random.randint(1,10+1)


8

In [103]:
np.random.rand(3,2,3)

array([[[0.60149119, 0.36607932, 0.12250596],
        [0.59025432, 0.74166697, 0.44704186]],

       [[0.9439334 , 0.12853488, 0.9650509 ],
        [0.19166421, 0.17738925, 0.73244145]],

       [[0.85933691, 0.60098068, 0.86944874],
        [0.63819103, 0.13315122, 0.68277871]]])

In [104]:
np.save("newArray", newArray)

In [112]:
np.savetxt("newArray1", np.ones(4))

In [114]:
np.loadtxt("newArray1")

array([1., 1., 1., 1.])